#!/bin/bash
git pull
in_group=( `cat local_group.txt`)
parent=(`hostname`)
obs=(`/home/obs/bin/whereami`)
k=1
for i in "${in_group[@]}" 
do
[[ ping $i -c 1 ]]  
    if [ $? -eq 0 ] 
    then
    	printf "_________ %s __________ System number %d\n" "$i" "$k" 
        ((k++))
        ssh $i "cd ~/glance && python create_all_data.py"
    fi 
done

rm -f MegaSAS.log
git add *
git commit -m "Regular commit by $HOSTNAME on the ${obs} network at `date`"
git push
