#!/bin/bash

in_group=( `cat local_group.txt`)
parent=(`hostname`)
obs=(`/home/obs/bin/whereami`)
k=1
for i in "${in_group[@]}" 
do
    printf "_________ %s __________ %d of %d\n" "$i" "$k" "${#in_group[@]}"
    ((k++))
    ssh $i "cd ~/glance && pyhton create_all_data.py" 
done


git add *
git commit -m "Regular commit by $HOSTNAME on the ${obs} network at `date`"
git push
